import type { activityLog } from "./activity";
import type { bankAccount, yieldConfig } from "./bank-accounts";
import type { bill } from "./bills";
import type { category } from "./categories";
import type { creditCard } from "./credit-cards";
import type { exchangeRate } from "./exchange-rates";
import type { income, incomeOverride } from "./income";
import type { purchasePlan } from "./plans";
import type { recurringExpense } from "./recurring";
import type { userSettings } from "./settings";

export type BankAccount = typeof bankAccount.$inferSelect;
export type NewBankAccount = typeof bankAccount.$inferInsert;
export type YieldConfig = typeof yieldConfig.$inferSelect;
export type NewYieldConfig = typeof yieldConfig.$inferInsert;
export type CreditCard = typeof creditCard.$inferSelect;
export type NewCreditCard = typeof creditCard.$inferInsert;
export type ExchangeRate = typeof exchangeRate.$inferSelect;
export type NewExchangeRate = typeof exchangeRate.$inferInsert;
export type Category = typeof category.$inferSelect;
export type NewCategory = typeof category.$inferInsert;
export type Bill = typeof bill.$inferSelect;
export type NewBill = typeof bill.$inferInsert;
export type RecurringExpense = typeof recurringExpense.$inferSelect;
export type NewRecurringExpense = typeof recurringExpense.$inferInsert;
export type Income = typeof income.$inferSelect;
export type NewIncome = typeof income.$inferInsert;
export type IncomeOverride = typeof incomeOverride.$inferSelect;
export type NewIncomeOverride = typeof incomeOverride.$inferInsert;
export type PurchasePlan = typeof purchasePlan.$inferSelect;
export type NewPurchasePlan = typeof purchasePlan.$inferInsert;
export type ActivityLog = typeof activityLog.$inferSelect;
export type NewActivityLog = typeof activityLog.$inferInsert;
export type UserSettings = typeof userSettings.$inferSelect;
export type NewUserSettings = typeof userSettings.$inferInsert;
